'use strict';

module.exports = {
  acl: 'private',
  resize: true,
  extract: false,
  trim: false,
  flatten: false,
  extend: false,
  negate: false,
  rotate: false,
  flip: false,
  flop: false,
  blur: false,
  sharpen: false,
  gamma: false,
  grayscale: false,
  greyscale: false,
  normalize: false,
  normalise: false,
  withMetadata: false,
  convolve: false,
  threshold: false,
  toColourspace: false,
  toColorspace: false,
  toFormat: false,
  gzip: false,
  metadata: {},
  composite: false,
  ensureAlpha: false,
  modulate: false
};
